<?php

namespace Social\ManagerBundle\Entity;

/**
 * TokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokensRepository extends \Doctrine\ORM\EntityRepository {

    public function _getCountListByUser($user_id) {
        $q = 'SELECT c FROM SocialManagerBundle:Tokens c';
        $q .= ' WHERE c.u_id =' . $user_id;
        $total = $this->getEntityManager()->createQuery($q)->getResult();
        return count($total);
    }

    public function _getProListByUser($user_id, $page = 1, $limit = 12) {
        $q = 'SELECT c FROM SocialManagerBundle:Tokens c ';
        $q .= ' WHERE c.u_id =' . $user_id;
        $q .= ' ORDER BY c.id DESC';
        return $this->getEntityManager()
                        ->createQuery($q)
                        ->setMaxResults($limit)
                        ->setFirstResult(($page - 1) * $limit)
                        ->getResult();
    }

    public function _getCountListByAdmin() {
        $q = 'SELECT c FROM SocialManagerBundle:Tokens c';
        $total = $this->getEntityManager()->createQuery($q)->getResult();
        return count($total);
    }

    public function _getProListByAdmin($page = 1, $limit = 12) {
        $q = 'SELECT c FROM SocialManagerBundle:Tokens c ';
        $q .= ' ORDER BY c.id DESC';
        return $this->getEntityManager()
                        ->createQuery($q)
                        ->setMaxResults($limit)
                        ->setFirstResult(($page - 1) * $limit)
                        ->getResult();
    }

}
