<?php

namespace Social\ManagerBundle\Entity;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateUsers($param, $id, $total = 1) {
        $q = "UPDATE SocialManagerBundle:Users c  SET $param = $param + $total WHERE c.id = $id";
        $this->getEntityManager()->createQuery($q)->execute();
    }

    public function _getCountAdmin() {
        $q = 'SELECT count(c.id) FROM SocialManagerBundle:Users c';
        $total = $this->getEntityManager()
                ->createQuery($q)
                ->getResult();
        return $total[0][1];
    }

    public function _getProAdmin($page, $limit) {
        $q = 'SELECT c FROM SocialManagerBundle:Users c';
        return $this->getEntityManager()
                        ->createQuery($q)
                        ->setMaxResults($limit)
                        ->setFirstResult(($page - 1) * $limit)
                        ->getResult();
    }

    public function _getCountListByAdmin() {
        $q = 'SELECT c FROM SocialManagerBundle:Users c';
        $total = $this->getEntityManager()->createQuery($q)->getResult();
        return count($total);
    }

    public function _getProListByAdmin($page = 1, $limit = 12) {
        $q = 'SELECT c FROM SocialManagerBundle:Users c ';
        $q .= ' ORDER BY c.id DESC';
        return $this->getEntityManager()
                        ->createQuery($q)
                        ->setMaxResults($limit)
                        ->setFirstResult(($page - 1) * $limit)
                        ->getResult();
    }
}
